### ISSUE TITLE
问一下环境怎么弄,Linux

### ISSUE THREAD

**Issue by PlexPt** [wongsyrone/shadowsocks-android#3]
编译不了

**Comment by wongsyrone** [comment]
https://github.com/wongsyrone/shadowsocks-android#build

**Comment by wongsyrone** [comment]
另外sbt什么的下载包需要翻墙

**Comment by wongsyrone** [comment]
你这个版本是有多老，已经不用openssl了，换mbedtls了，还是删掉重新clone一次吧

**Comment by wongsyrone** [comment]
如果编译不了，去看travis ci的配置，或者去releases直接下载编译好的。

**Comment by PlexPt** [comment]
##### Building Go toolchain using /opt/go/bin.
[error] bootstrap/internal/sys
[error] bootstrap/asm/internal/flags
[error] bootstrap/compile/internal/big
[error] bootstrap/internal/bio
[error] bootstrap/internal/gcprog
[error] bootstrap/internal/obj
[error] bootstrap/internal/obj/arm
[error] bootstrap/internal/obj/arm64
[error] bootstrap/internal/obj/mips
[error] bootstrap/internal/obj/ppc64
[error] bootstrap/internal/obj/s390x
[error] bootstrap/internal/obj/x86
[error] bootstrap/asm/internal/lex
[error] bootstrap/link/internal/ld
[error] bootstrap/compile/internal/ssa
[error] bootstrap/asm/internal/arch
[error] bootstrap/asm/internal/asm
[warn] UPDATE: A newer sbt-android is available: 1.7.7, currently running: 1.7.2
[error] bootstrap/asm
[warn] Android SDK updates available, run 'android-update' to update:
[warn]     Android SDK Tools
[warn]     Google Repository
[warn]     Android SDK Platform-Tools
[error] bootstrap/link/internal/arm
[error] bootstrap/link/internal/amd64
[error] bootstrap/link/internal/arm64
[error] bootstrap/link/internal/mips64
[error] bootstrap/link/internal/ppc64
[error] bootstrap/link/internal/s390x
[error] bootstrap/link/internal/x86
[error] bootstrap/link
[error] bootstrap/compile/internal/gc
[error] bootstrap/compile/internal/amd64
[error] bootstrap/compile/internal/arm
[error] bootstrap/compile/internal/arm64
[error] bootstrap/compile/internal/mips64
[error] bootstrap/compile/internal/ppc64
[error] bootstrap/compile/internal/s390x
[error] bootstrap/compile/internal/x86
[error] bootstrap/compile
[info] 
[info] ##### Building go_bootstrap for host, linux/amd64.
[error] runtime/internal/sys
[error] runtime/internal/atomic
[error] runtime
[error] unicode/utf16
[error] unicode/utf8
[error] encoding
[error] internal/race
[error] sync/atomic
[error] errors
[error] sort
[error] unicode
[error] math
[error] internal/syscall/windows/sysdll
[error] sync
[error] internal/singleflight
[error] io
[error] syscall
[error] container/heap
[error] hash
[error] hash/adler32
[error] strings
[error] bytes
[error] strconv
[error] bufio
[error] path
[error] reflect
[error] crypto
[error] encoding/base64
[error] regexp/syntax
[error] crypto/sha1
[error] internal/syscall/windows/registry
[error] time
[error] internal/syscall/windows
[error] regexp
[error] os
[error] os/signal
[error] path/filepath
[error] encoding/binary
[error] fmt
[error] io/ioutil
[error] go/token
[error] debug/dwarf
[error] compress/flate
[error] net/url
[error] encoding/json
[error] text/template/parse
[error] context
[error] flag
[error] log
[error] go/scanner
[error] os/exec
[error] go/ast
[error] text/template
[error] compress/zlib
[error] debug/macho
[error] debug/elf
[error] go/parser
[error] go/doc
[error] go/build
[error] cmd/go
[info] 
[info] ##### Building packages and commands for linux/amd64.
[error] runtime/internal/sys
[error] runtime/internal/atomic
[error] runtime
[error] errors
[error] internal/race
[error] sync/atomic
[error] unicode
[error] unicode/utf8
[error] math
[error] sync
[error] sort
[error] container/heap
[error] io
[error] syscall
[error] hash
[error] hash/adler32
[error] hash/crc32
[error] bytes
[error] strings
[error] bufio
[error] strconv
[error] text/tabwriter
[error] path
[error] compress/bzip2
[error] container/list
[error] time
[error] container/ring
[error] reflect
[error] regexp/syntax
[error] crypto
[error] crypto/subtle
[error] crypto/cipher
[error] crypto/aes
[error] math/rand
[error] os
[error] crypto/sha512
[error] regexp
[error] crypto/hmac
[error] crypto/md5
[error] internal/syscall/unix
[error] crypto/rc4
[error] path/filepath
[error] crypto/sha1
[error] crypto/sha256
[error] encoding/base64
[error] io/ioutil
[error] internal/nettrace
[error] internal/singleflight
[error] encoding/pem
[error] encoding
[error] encoding/ascii85
[error] encoding/base32
[error] unicode/utf16
[error] vendor/golang_org/x/net/lex/httplex
[error] hash/crc64
[error] hash/fnv
[error] html
[error] image/color
[error] internal/syscall/windows/sysdll
[error] runtime/debug
[error] encoding/binary
[error] fmt
[error] image
[error] image/color/palette
[error] cmd/internal/sys
[error] crypto/des
[error] index/suffixarray
[error] runtime/trace
[error] image/internal/imageutil
[error] math/cmplx
[error] os/signal
[error] image/draw
[error] flag
[error] log
[error] debug/dwarf
[error] compress/flate
[error] debug/gosym
[error] cmd/internal/obj
[error] debug/plan9obj
[error] cmd/vendor/golang.org/x/arch/arm/armasm
[error] compress/zlib
[error] debug/macho
[error] debug/elf
[error] cmd/internal/goobj
[error] debug/pe
[error] cmd/vendor/golang.org/x/arch/x86/x86asm
[error] archive/tar
[error] archive/zip
[error] compress/gzip
[error] compress/lzw
[error] context
[error] math/big
[error] encoding/hex
[error] go/token
[error] os/exec
[error] go/scanner
[error] go/ast
[error] cmd/internal/objfile
[error] database/sql/driver
[error] database/sql
[error] cmd/addr2line
[error] encoding/csv
[error] crypto/dsa
[error] crypto/elliptic
[error] encoding/asn1
[error] crypto/rand
[error] crypto/rsa
[error] go/parser
[error] crypto/x509/pkix
[error] go/printer
[error] crypto/ecdsa
[error] encoding/gob
[error] encoding/json
[error] encoding/xml
[error] cmd/cgo
[error] vendor/golang_org/x/net/http2/hpack
[error] mime
[error] mime/quotedprintable
[error] net/http/internal
[error] net/url
[error] text/template/parse
[error] go/constant
[error] go/format
[error] text/scanner
[error] image/gif
[error] go/types
[error] image/jpeg
[error] text/template
[error] image/png
[error] runtime/pprof
[error] go/doc
[error] html/template
[error] runtime/cgo
[error] go/build
[error] testing
[error] internal/trace
[error] internal/testenv
[error] net/internal/socktest
[error] net
[error] os/user
[error] runtime/race
[error] testing/iotest
[error] testing/quick
[error] go/internal/gccgoimporter
[error] go/internal/gcimporter
[error] cmd/api
[error] go/importer
[error] cmd/internal/obj/arm
[error] cmd/internal/obj/arm64
[error] cmd/internal/obj/mips
[error] cmd/internal/obj/ppc64
[error] cmd/internal/obj/s390x
[error] cmd/internal/obj/x86
[error] cmd/asm/internal/flags
[error] cmd/asm/internal/lex
[error] crypto/x509
[error] net/textproto
[error] net/http/httptrace
[error] log/syslog
[error] mime/multipart
[error] net/mail
[error] cmd/internal/bio
[error] cmd/compile/internal/big
[error] cmd/compile/internal/ssa
[error] crypto/tls
[error] cmd/asm/internal/arch
[error] cmd/internal/gcprog
[error] cmd/asm/internal/asm
[error] cmd/compile/internal/test
[error] cmd/cover
[error] net/http
[error] net/smtp
[error] cmd/asm
[error] cmd/dist
[error] cmd/doc
[error] cmd/fix
[error] cmd/gofmt
[error] cmd/internal/pprof/profile
[error] cmd/internal/pprof/svg
[error] cmd/internal/pprof/tempfile
[error] cmd/link/internal/ld
[error] expvar
[error] net/http/cgi
[error] net/http/cookiejar
[error] net/http/httptest
[error] net/http/fcgi
[error] net/http/httputil
[error] net/http/pprof
[error] net/rpc
[error] cmd/compile/internal/gc
[error] cmd/go
[error] net/rpc/jsonrpc
[error] cmd/internal/pprof/plugin
[error] cmd/internal/pprof/report
[error] cmd/internal/pprof/commands
[error] cmd/internal/pprof/driver
[error] cmd/internal/pprof/fetch
[error] cmd/internal/pprof/symbolizer
[error] cmd/internal/pprof/symbolz
[error] cmd/nm
[error] cmd/link/internal/amd64
[error] cmd/link/internal/arm
[error] cmd/link/internal/arm64
[error] cmd/link/internal/mips64
[error] cmd/link/internal/ppc64
[error] cmd/link/internal/s390x
[error] cmd/link/internal/x86
[error] cmd/objdump
[error] cmd/link
[error] cmd/pack
[error] cmd/pprof
[error] cmd/trace
[error] cmd/vet/internal/cfg
[error] cmd/vet/internal/whitelist
[error] cmd/vet
[error] cmd/yacc
[error] cmd/compile/internal/amd64
[error] cmd/compile/internal/arm
[error] cmd/compile/internal/arm64
[error] cmd/compile/internal/mips64
[error] cmd/compile/internal/ppc64
[error] cmd/compile/internal/s390x
[error] cmd/compile/internal/x86
[error] cmd/compile
[info] 
[info] 
[info] ---
[info] Installed Go for linux/amd64 in /home/pt/project/ms/shadowsocks-android/kcptun/go
[info] Installed commands in /home/pt/project/ms/shadowsocks-android/kcptun/go/bin
[info] ~/project/ms/shadowsocks-android/kcptun
[info] ~/project/ms/shadowsocks-android/kcptun/kcptun/client ~/project/ms/shadowsocks-android/kcptun
[info] Get dependences for kcptun
